/**********************************************************************************************************************
 *  Description: interface between router agents and SDK service manager
 *
 *  Copyright (c) 2018 Nokia
 **********************************************************************************************************************/

// NDK Version: v0.5.0

syntax = "proto3";

package srlinux.sdk;

import "ndk/sdk_common.proto";

option go_package = "github.com/nokia/srlinux-ndk-go/ndk";

/**
 * Represents network instance subscription request.
 */
message NetworkInstanceSubscriptionRequest {}

/**
 * Represents network instance key.
 */
message NetworkInstanceKey {
  string instance_name = 1; // Network instance name
}

/**
 * Represents network instance data.
 */
message NetworkInstanceData {
  uint32 network_instance_id = 1; /* Network instance identifier */
  string base_name = 2; // Base name
  bool oper_is_up = 4; // Operation status
  string router_id = 5; // Router identifier
  // Represents network instance type.
  enum NetworkInstanceType {
    NETWORK_INSTANCE_TYPE_DEFAULT = 0; // Default network instance type
    NETWORK_INSTANCE_TYPE_L3VRF = 1; // L3VRF network instance type
  }
  NetworkInstanceType instance_type = 6; // Network instance type
}

/**
 * Represents network instance notification.
 */
message NetworkInstanceNotification {
  SdkMgrOperation op = 1; // Operation such as create, delete, or update
  NetworkInstanceKey key = 2; // Network key
  NetworkInstanceData data = 3; // Network data
}
